// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace RESTAURANTE.Features.Atencion
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("AtencionSinMesa")]
    [NUnit.Framework.FixtureLifeCycleAttribute(NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class AtencionSinMesaFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Atencion", "AtencionSinMesa", "A short summary of the feature\r\n| Orden\t\t| Concepto\t\t\t\t\t\t\t\t\t\t| Cantidad\t| Anotaci" +
                "on\t\t\t|\r\n| CODIGO\t| 7\t\t\t\t\t\t\t\t\t\t\t\t| -\t\t\t| -\t\t\t\t\t|\r\n| ITEM\t\t| ADICIONAL 1/2 PORCIÓN" +
                " DE CANCHITA\t\t\t\t\t| 2\t\t\t| -\t\t\t\t\t|", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "AtencionSinMesa.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Atencion de una orden sin mesa - DELIVERY")]
        [NUnit.Framework.CategoryAttribute("AtencionSinMesa")]
        public async System.Threading.Tasks.Task AtencionDeUnaOrdenSinMesa_DELIVERY()
        {
            string[] tagsOfScenario = new string[] {
                    "AtencionSinMesa"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Atencion de una orden sin mesa - DELIVERY", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 9
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 10
 await testRunner.GivenAsync("Inicio de sesión con usuario \'admin@tintoymadero.com\' y contraseña \'calidad\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 11
 await testRunner.AndAsync("Se ingresa al módulo \'Atencion\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 12
 await testRunner.AndAsync("Se seleciona el tipo de atencion \'SIN MESA\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 13
 await testRunner.AndAsync("Se seleciona el modo \'DELIVERY\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 14
 await testRunner.AndAsync("Se ingresa el cliente \'LEONARDO\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 15
 await testRunner.AndAsync("Se selecciona el mozo \'JAVIER STANLY CISNEROS SANCHEZ\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "Orden",
                            "Concepto",
                            "Cantidad",
                            "Anotacion"});
                table2.AddRow(new string[] {
                            "ITEM",
                            "8|CARTA ANTICUCHO A LA PARRILLA",
                            "1",
                            "Anotacion 1"});
                table2.AddRow(new string[] {
                            "CODIGO",
                            "9|CARTA MOLLEJAS A LA PARRILLA",
                            "1",
                            ""});
                table2.AddRow(new string[] {
                            "ITEM",
                            "23|CARTA MILANESA DE POLLO",
                            "2",
                            ""});
                table2.AddRow(new string[] {
                            "CODIGO",
                            "8|CARTA ANTICUCHO A LA PARRILLA",
                            "1",
                            "Anotacion 3"});
                table2.AddRow(new string[] {
                            "ITEM",
                            "17|CARTA TEQUEÑOS EN SALSA DE HUACAMOLE",
                            "2",
                            "Anotacion 4"});
#line 16
 await testRunner.WhenAsync("Se ingresa las siguientes ordenes:", ((string)(null)), table2, "When ");
#line hidden
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "Accion",
                            "Concepto",
                            "Cantidad",
                            "Anotacion"});
                table3.AddRow(new string[] {
                            "Agregar anotacion",
                            "CARTA MOLLEJAS A LA PARRILLA",
                            "1",
                            "Anotacion 2"});
                table3.AddRow(new string[] {
                            "Eliminar",
                            "CARTA MILANESA DE POLLO",
                            "2",
                            ""});
#line 24
 await testRunner.AndAsync("Se realiza la siguiente modificacion a la orden:", ((string)(null)), table3, "And ");
#line hidden
#line 29
 await testRunner.ThenAsync("Se procede a \'Guardar\' la orden", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Atencion de una orden sin mesa - AL PASO")]
        [NUnit.Framework.CategoryAttribute("AtencionSinMesa")]
        public async System.Threading.Tasks.Task AtencionDeUnaOrdenSinMesa_ALPASO()
        {
            string[] tagsOfScenario = new string[] {
                    "AtencionSinMesa"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Atencion de una orden sin mesa - AL PASO", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 32
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 33
 await testRunner.GivenAsync("Inicio de sesión con usuario \'admin@tintoymadero.com\' y contraseña \'calidad\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 34
 await testRunner.AndAsync("Se ingresa al módulo \'Atencion\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 35
 await testRunner.AndAsync("Se seleciona el tipo de atencion \'SIN MESA\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 36
 await testRunner.AndAsync("Se seleciona el modo \'AL PASO\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 37
 await testRunner.AndAsync("Se ingresa el cliente \'LEONARDO\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 38
 await testRunner.AndAsync("Se selecciona el mozo \'JAVIER STANLY CISNEROS SANCHEZ\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "Orden",
                            "Concepto",
                            "Cantidad",
                            "Anotacion"});
                table4.AddRow(new string[] {
                            "ITEM",
                            "8|CARTA ANTICUCHO A LA PARRILLA",
                            "1",
                            "Sin ensalada"});
                table4.AddRow(new string[] {
                            "CODIGO",
                            "9|CARTA MOLLEJAS A LA PARRILLA",
                            "1",
                            ""});
                table4.AddRow(new string[] {
                            "ITEM",
                            "8|CARTA ANTICUCHO A LA PARRILLA",
                            "4",
                            "Sin ensalada"});
#line 39
 await testRunner.WhenAsync("Se ingresa las siguientes ordenes:", ((string)(null)), table4, "When ");
#line hidden
#line 45
 await testRunner.ThenAsync("Se procede a \'Guardar\' la orden", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Buscar orden")]
        [NUnit.Framework.CategoryAttribute("AtencionSinMesa")]
        public async System.Threading.Tasks.Task BuscarOrden()
        {
            string[] tagsOfScenario = new string[] {
                    "AtencionSinMesa"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Buscar orden", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 48
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 49
 await testRunner.GivenAsync("Inicio de sesión con usuario \'admin@tintoymadero.com\' y contraseña \'calidad\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 50
 await testRunner.AndAsync("Se ingresa al módulo \'Atencion\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 51
 await testRunner.AndAsync("Se seleciona el tipo de atencion \'SIN MESA\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "Alias",
                            "Modo",
                            "Total"});
                table5.AddRow(new string[] {
                            "LEONARDO",
                            "DELIVERY",
                            "246.00"});
#line 52
 await testRunner.AndAsync("Se selecciona el siguiente pedido:", ((string)(null)), table5, "And ");
#line hidden
#line 55
 await testRunner.AndAsync("Se realiza la accion de \'Atender\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
